CREATE TABLE items ( 
    id number NOT NULL,
    CONSTRAINT pk_items_id PRIMARY KEY(id),
    name varchar2(30) NOT NULL,
    CONSTRAINT UNIQUE_ITEMS_NAME UNIQUE (name),
    QuantityAvailable NUMBER NOT NULL,
    price NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(300) NOT NULL
  );
  CREATE SEQUENCE  "items_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ;
  CREATE OR REPLACE TRIGGER "items_TRG" 
  BEFORE INSERT ON items 
  FOR EACH ROW 
  BEGIN
    <<COLUMN_SEQUENCES>>
    BEGIN
      IF INSERTING AND :NEW.id IS NULL THEN
        SELECT "items_SEQ".NEXTVAL INTO :NEW.id FROM SYS.DUAL;
      END IF;
    END COLUMN_SEQUENCES;
  END;
  
 CREATE TABLE CartRecords ( 
    id number,
    CONSTRAINT pk_CartRecords_id PRIMARY KEY(id),
    cartId number NOT NULL,
    itemId number NOT NULL,
    CONSTRAINT fk_CartRecords_itemId FOREIGN KEY(itemId) REFERENCES items(id),
    quantityRequested number NOT NULL
  );
  CREATE SEQUENCE  "CartRecords_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ;
  CREATE OR REPLACE TRIGGER "CartRecords_TRG" 
  BEFORE INSERT ON CartRecords 
  FOR EACH ROW 
  BEGIN
    <<COLUMN_SEQUENCES>>
    BEGIN
      IF INSERTING AND :NEW.id IS NULL THEN
        SELECT "CartRecords_SEQ".NEXTVAL INTO :NEW.id FROM SYS.DUAL;
      END IF;
    END COLUMN_SEQUENCES;
  END;
commit;