create or replace PROCEDURE GET_ISSUEUPDATES_BY_ISSUEID
(
  i_issueId IN NUMBER,
  o_recordset OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN o_recordset FOR  
    SELECT ISSUEUPDATEID, ISSUEID, SUBMITTEDBY, USERNAME, UPDATEDATE, UPDATECOMMENT 
	FROM ISSUEUPDATES 
	JOIN USERS ON
	SUBMITTEDBY = USERID
	where ISSUEID = i_issueId;
END GET_ISSUEUPDATES_BY_ISSUEID;