CREATE OR REPLACE PROCEDURE GET_ROLES_BY_USERID
(
	i_userId IN number,
  	o_recordset OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN o_recordset FOR
    SELECT ROL.ROLEID, ROL.ROLENAME 
	FROM ROLES ROL
	JOIN USERROLES UR ON
	UR.ROLEID = ROL.ROLEID
	JOIN USERS US ON
	UR.USERID = US.USERID
	where US.USERID = i_userId
	ORDER BY ROL.ROLEID;
END GET_ROLES_BY_USERID;