CREATE OR REPLACE PROCEDURE REMOVE_ISSUEUPDATE_BY_ISSUEID
(
  i_issueId IN NUMBER
)
IS
BEGIN
  DELETE FROM ISSUEUPDATES WHERE issueId = i_issueId;  
  COMMIT;
END REMOVE_ISSUEUPDATE_BY_ISSUEID;