CREATE OR REPLACE PROCEDURE REMOVE_ISSUE
(
  i_issueid IN NUMBER
)
IS
BEGIN
	DELETE FROM ISSUEUPDATES WHERE issueId = i_issueId;  
	DELETE FROM ISSUES WHERE issueid = i_issueid;
	COMMIT;
END REMOVE_ISSUE;